### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by steelbrain** [cho45/named-regexp.js#2]
I found your library via npm while looking for XRegExp alternatives. Your project looks great but I wasn't able to make it work with some regexpes of ours, we could really use your expertise.
If you could just make you library work with linter's RegExps; A few sample of them look like

``` js
'.+:\\s*' +
'(line (?<line>\\d+), col (?<col>\\d+), )?' +
'((?<error>Error)|(?<warning>Warning)) - (?<message>.*)'
// or
'(?<file>.+):(?<line>\\d+):(?<col>\\d+):\\s+((((?<error>E)|(?<warning>[CDFNW]))(?<code>\\d+)(:\\s+|\\s+))|(.*?))(?<message>.+)(\r)?\n'
// or
'line (?<line>[0-9]+), col (?<col>[0-9]+): (?<message>.+)'
```

We can make our RegExps adapt to your syntax if you could guide us.
You can find more in the [AtomLinter org](https://github.com/AtomLinter). If you could make your library work with that, I can guarantee you fame and thousands of downloads.

**Comment by edvinv** [comment]
@steelbrain, Hi, I was also looking for XRegExp replacement and came to this project but found that is not working with some more complicated patterns. So I created this [named-js-regexp](https://github.com/edvinv/named-js-regexp). I tested your samples and are working ok.

**Comment by steelbrain** [comment]
@edvinv Thanks, I'll be suggesting it to the team and will let you know if it works for us
